# Generated by Django 4.2.1 on 2023-06-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_rus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('water', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('ngk', models.FloatField()),
                ('hol', models.FloatField()),
                ('mds', models.FloatField()),
                ('krahmal', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('fiber', models.FloatField()),
                ('ok', models.FloatField()),
                ('zola', models.FloatField()),
                ('Na', models.FloatField()),
                ('Ka', models.FloatField()),
                ('Ca', models.FloatField()),
                ('Mg', models.FloatField()),
                ('P', models.FloatField()),
                ('Fe', models.FloatField()),
                ('A1', models.FloatField()),
                ('b_car', models.FloatField()),
                ('A', models.FloatField()),
                ('E', models.FloatField()),
                ('B1', models.FloatField()),
                ('B2', models.FloatField()),
                ('PP1', models.FloatField()),
                ('PP', models.FloatField()),
                ('C', models.FloatField()),
                ('energy', models.FloatField()),
            ],
        ),
    ]
