# Generated by Django 4.2.1 on 2023-06-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CookingMethod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('prepare_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('hot_or_cold', models.CharField(max_length=255)),
                ('cooking_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.cookingmethod')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.intake')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='SizeName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('kfa', models.FloatField()),
                ('goal_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WorldKitchen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='food_rus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WeightLoss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cooking_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.cookingcondition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.product')),
                ('size_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.sizename')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategoryName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('recipes', models.ManyToManyField(through='healthapp.RecipeCategory', to='healthapp.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='recipe_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.recipecategoryname'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.userinfo'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='world_kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.worldkitchen'),
        ),
        migrations.CreateModel(
            name='ProductNutrient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('nutrient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.nutrientname')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.unit')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.source'),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('imageURL', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CookingLoss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cooking_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.cookingcondition')),
                ('nutrient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.nutrientname')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.product')),
            ],
        ),
    ]
