# Generated by Django 4.2.1 on 2023-06-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_productname_remove_product_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.source'),
        ),
    ]
