# Generated by Django 4.2.1 on 2023-06-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0010_alter_recipe_cook_time_alter_recipe_cooking_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='imageURL',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='size_name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.sizename'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.unit'),
        ),
    ]
