# Generated by Django 4.2.1 on 2023-06-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0011_alter_instruction_imageurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='size_name_id',
            new_name='size_name',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='cooking_condition',
        ),
    ]
